### ISSUE TITLE
Fix URL re-routing

### ISSUE THREAD

**Issue by JessicaG** [pgoulding/pgoulding.github.io#5]
Move your hosting to something like Netlify and point your DNS records for pgoulding.dev to them. Will be cleaner. 

https://dev.to/lindakatcodes/a-beginners-guide-to-hosting-an-app-with-heroku-and-netlify-8i5

Free plan should wok: https://www.netlify.com/pricing/

**Comment by pgoulding** [comment]
Hosted on Netlify as www.pgoulding.dev with redirects from patrickgoulding.com pgoulding.com, patrickgoulding.dev
